import type { Property } from "@/types/property";

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "1",
    title: "3-к квартира в центре Грозного",
    price: 8500000,
    currency: "RUB",
    location: "Грозный, пр. Путина, 12",
    region: "Chechnya",
    type: "apartment",
    rooms: 3,
    area: 85,
    image: "https://picsum.photos/800/600?random=1",
    isPremium: true,
    datePosted: "2023-10-25",
    description:
      'Просторная квартира с евроремонтом в самом центре города. Вид на мечеть "Сердце Чечни".',
    features: ["Евроремонт", "Кондиционер", "Парковка", "Лифт"],
    contact: {
      name: "Магомед",
      phone: "+7 (928) 000-00-01",
    },
    images: [
      "https://picsum.photos/800/600?random=1",
      "https://picsum.photos/800/600?random=2",
      "https://picsum.photos/800/600?random=3",
    ],
    pricePerMeter: 100000,
    floor: "5",
    totalFloors: 9,
    views: 1240,
    status: "active",
    userId: "user-1",
    createdAt: "2023-10-25T00:00:00Z",
    updatedAt: "Сегодня, 14:30",
  },
  {
    id: "2",
    title: "Дом в Назрани, район Центр-Камаз",
    price: 12000000,
    currency: "RUB",
    location: "Назрань, ул. Муталиева",
    region: "Ingushetia",
    type: "house",
    rooms: 5,
    area: 220,
    image: "https://picsum.photos/800/600?random=4",
    isPremium: true,
    datePosted: "2023-10-24",
    description:
      "Двухэтажный кирпичный дом с большим двором и садом. Все коммуникации подведены.",
    features: ["Гараж", "Сад", "Подвал", "Газ", "Вода"],
    contact: {
      name: "Ибрагим",
      phone: "+7 (928) 000-00-02",
    },
    images: ["https://picsum.photos/800/600?random=4", "https://picsum.photos/800/600?random=5"],
    pricePerMeter: 54545,
    floor: "1",
    views: 890,
    status: "active",
    userId: "user-2",
    createdAt: "2023-10-24T00:00:00Z",
    updatedAt: "Вчера, 10:15",
  },
  {
    id: "3",
    title: "Участок 10 соток в Магасе",
    price: 3500000,
    currency: "RUB",
    location: "Магас, 8-й микрорайон",
    region: "Ingushetia",
    type: "land",
    area: 1000,
    image: "https://picsum.photos/800/600?random=6",
    isPremium: false,
    datePosted: "2023-10-23",
    description:
      "Ровный участок под ИЖС в перспективном районе столицы. Рядом школа и садик.",
    features: ["ИЖС", "Свет", "Газ по меже"],
    contact: {
      name: "Ахмед",
      phone: "+7 (928) 000-00-03",
    },
    images: ["https://picsum.photos/800/600?random=6"],
    views: 456,
    status: "active",
    userId: "user-3",
    createdAt: "2023-10-23T00:00:00Z",
    updatedAt: "2 дня назад",
  },
  {
    id: "4",
    title: "2-к квартира в Аргуне",
    price: 4200000,
    currency: "RUB",
    location: "Аргун, ул. Кадырова",
    region: "Chechnya",
    type: "apartment",
    rooms: 2,
    area: 54,
    image: "https://picsum.photos/800/600?random=7",
    isPremium: false,
    datePosted: "2023-10-22",
    description: 'Уютная квартира в новом доме. Рядом мечеть "Сердце Матери".',
    features: ["Новостройка", "Балкон"],
    contact: {
      name: "Фатима",
      phone: "+7 (928) 000-00-04",
    },
    images: ["https://picsum.photos/800/600?random=7"],
    pricePerMeter: 77778,
    floor: "3",
    totalFloors: 5,
    views: 678,
    status: "active",
    userId: "user-4",
    createdAt: "2023-10-22T00:00:00Z",
    updatedAt: "3 дня назад",
  },
  {
    id: "5",
    title: "Коттедж в горах (Джейрах)",
    price: 15000000,
    currency: "RUB",
    location: "Джейрахский район, с. Армхи",
    region: "Ingushetia",
    type: "house",
    rooms: 4,
    area: 150,
    image: "https://picsum.photos/800/600?random=8",
    isPremium: true,
    datePosted: "2023-10-20",
    description:
      "Живописное место, идеально для туристического бизнеса или отдыха.",
    features: ["Вид на горы", "Родник", "Туристическая зона"],
    contact: {
      name: "Руслан",
      phone: "+7 (928) 000-00-05",
    },
    images: ["https://picsum.photos/800/600?random=8"],
    pricePerMeter: 100000,
    floor: "1",
    views: 1234,
    status: "active",
    userId: "user-5",
    createdAt: "2023-10-20T00:00:00Z",
    updatedAt: "5 дней назад",
  },
  {
    id: "6",
    title: "1-к квартира, Минутка",
    price: 3800000,
    currency: "RUB",
    location: "Грозный, пл. Минутка",
    region: "Chechnya",
    type: "apartment",
    rooms: 1,
    area: 42,
    image: "https://picsum.photos/800/600?random=9",
    isPremium: false,
    datePosted: "2023-10-26",
    description:
      "Свежий ремонт, мебель остается. Отличная транспортная развязка.",
    features: ["Мебель", "Техника"],
    contact: {
      name: "Зарема",
      phone: "+7 (928) 000-00-06",
    },
    images: ["https://picsum.photos/800/600?random=9"],
    pricePerMeter: 90476,
    floor: "7",
    totalFloors: 12,
    views: 567,
    status: "active",
    userId: "user-6",
    createdAt: "2023-10-26T00:00:00Z",
    updatedAt: "Сегодня, 09:00",
  },
];
