/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/send-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отправить SMS-код на номер телефона */
        post: operations["AuthController_sendPhoneCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/phone/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Подтвердить код и залогиниться/зарегистрироваться */
        post: operations["AuthController_verifyPhoneCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/phone-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация по номеру телефона и паролю */
        post: operations["AuthController_registerWithPhoneAndPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/phone-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход по номеру телефона и паролю */
        post: operations["AuthController_loginWithPhoneAndPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth */
        get: operations["AuthController_googleAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth callback */
        get: operations["AuthController_googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/yandex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Yandex OAuth */
        get: operations["AuthController_yandexAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/yandex/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Yandex OAuth callback */
        get: operations["AuthController_yandexCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновление access token */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выход из системы */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить текущего пользователя */
        get: operations["AuthController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить профиль текущего пользователя */
        get: operations["UsersController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Обновить профиль текущего пользователя */
        patch: operations["UsersController_updateMe"];
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить пользователя по ID */
        get: operations["UsersController_getUserById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список объявлений с фильтрами */
        get: operations["PropertiesController_findAll"];
        put?: never;
        /** Создать объявление */
        post: operations["PropertiesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/properties/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Поиск объявлений */
        get: operations["PropertiesController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/properties/stats/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить статистику по категориям недвижимости */
        get: operations["PropertiesController_getCategoryStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/properties/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить объявление по ID */
        get: operations["PropertiesController_findOne"];
        put?: never;
        post?: never;
        /** Удалить объявление */
        delete: operations["PropertiesController_remove"];
        options?: never;
        head?: never;
        /** Обновить объявление */
        patch: operations["PropertiesController_update"];
        trace?: never;
    };
    "/api/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список избранного */
        get: operations["FavoritesController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/{propertyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить объявление в избранное */
        post: operations["FavoritesController_add"];
        /** Удалить объявление из избранного */
        delete: operations["FavoritesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить статистику */
        get: operations["AdminController_getStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список пользователей */
        get: operations["AdminController_getUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список объявлений */
        get: operations["AdminController_getProperties"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить роль пользователя */
        patch: operations["AdminController_updateUserRole"];
        trace?: never;
    };
    "/api/admin/properties/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить статус объявления */
        patch: operations["AdminController_updatePropertyStatus"];
        trace?: never;
    };
    "/api/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить пользователя */
        delete: operations["AdminController_deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/properties/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить объявление */
        delete: operations["AdminController_deleteProperty"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить аватар пользователя */
        post: operations["UploadController_uploadAvatar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить изображения для объявления */
        post: operations["UploadController_uploadImages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/property": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать или получить чат по объявлению */
        post: operations["ChatsController_createPropertyChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/support": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать или получить чат поддержки */
        post: operations["ChatsController_createSupportChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список чатов пользователя */
        get: operations["ChatsController_getUserChats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chatId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить сообщения чата с cursor pagination */
        get: operations["ChatsController_getChatMessages"];
        put?: never;
        /** Отправить сообщение */
        post: operations["ChatsController_sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chatId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Пометить все сообщения как прочитанные */
        post: operations["ChatsController_markMessagesAsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/support/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить все чаты поддержки (только для админов/поддержки) */
        get: operations["ChatsController_getSupportChats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chatId}/assign-support": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Назначить сотрудника поддержки в чат */
        post: operations["ChatsController_assignSupportAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список регионов */
        get: operations["RegionsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить регион по ID с городами */
        get: operations["RegionsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список городов */
        get: operations["CitiesController_findCities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SendPhoneCodeDto: {
            /**
             * @description Номер телефона в формате E.164
             * @example +79626404047
             */
            phone: string;
        };
        VerifyPhoneCodeDto: {
            /**
             * @description Номер телефона в формате E.164
             * @example +79626404047
             */
            phone: string;
            /**
             * @description Код из SMS
             * @example 379840
             */
            code: string;
        };
        RegisterPhonePasswordDto: {
            /**
             * @description Номер телефона в формате E.164
             * @example +79626404047
             */
            phone: string;
            /**
             * @description Пароль пользователя (минимум 8 символов)
             * @example StrongP@ssw0rd
             */
            password: string;
        };
        RefreshTokenDto: {
            refreshToken: string;
        };
        UserResponseDto: {
            id: string;
            email: string;
            name: string;
            phone?: string;
            avatar?: string;
            isPremium: boolean;
            role: string;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateUserDto: {
            /** @example John Doe */
            name?: string;
            /** @example +7 (928) 000-00-00 */
            phone?: string;
        };
        CreatePropertyDto: {
            /** @example Квартира в центре Грозного */
            title: string;
            /** @example 5000000 */
            price: number;
            /**
             * @default RUB
             * @enum {string}
             */
            currency: "RUB" | "USD";
            /** @example г. Грозный, ул. Ленина, д. 10 */
            location: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            regionId: string;
            /**
             * @description ID города (опционально)
             * @example 660e8400-e29b-41d4-a716-446655440001
             */
            cityId?: string;
            /** @enum {string} */
            type: "APARTMENT" | "HOUSE" | "LAND" | "COMMERCIAL";
            /** @example 3 */
            rooms?: number;
            /** @example 75.5 */
            area: number;
            /** @example Отличная квартира в центре города */
            description: string;
            /**
             * @example [
             *       "https://example.com/image1.jpg"
             *     ]
             */
            images: string[];
            /**
             * @example [
             *       "Балкон",
             *       "Лоджия",
             *       "Парковка"
             *     ]
             */
            features?: string[];
            /**
             * @description Широта
             * @example 43.3156
             */
            latitude?: number;
            /**
             * @description Долгота
             * @example 45.6949
             */
            longitude?: number;
        };
        PropertyResponseDto: {
            id: string;
            title: string;
            price: number;
            /** @enum {string} */
            currency: "RUB" | "USD";
            location: string;
            regionId: string;
            /** @description Region relation (optional, may be included in response) */
            region?: Record<string, never>;
            /** @description ID города */
            cityId?: string;
            /** @description Город (если указан) */
            city?: Record<string, never>;
            /** @enum {string} */
            type: "APARTMENT" | "HOUSE" | "LAND" | "COMMERCIAL";
            rooms?: number;
            area: number;
            description: string;
            images: string[];
            features: string[];
            /** @enum {string} */
            status: "ACTIVE" | "PENDING" | "SOLD" | "ARCHIVED";
            views: number;
            userId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description Широта */
            latitude?: number;
            /** @description Долгота */
            longitude?: number;
        };
        UpdatePropertyDto: {
            /** @example Квартира в центре Грозного */
            title?: string;
            /** @example 5000000 */
            price?: number;
            /** @enum {string} */
            currency?: "RUB" | "USD";
            /** @example г. Грозный, ул. Ленина, д. 10 */
            location?: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            regionId?: string;
            /**
             * @description ID города (опционально)
             * @example 660e8400-e29b-41d4-a716-446655440001
             */
            cityId?: string;
            /** @enum {string} */
            type?: "APARTMENT" | "HOUSE" | "LAND" | "COMMERCIAL";
            /** @example 3 */
            rooms?: number;
            /** @example 75.5 */
            area?: number;
            /** @example Отличная квартира в центре города */
            description?: string;
            /**
             * @example [
             *       "https://example.com/image1.jpg"
             *     ]
             */
            images?: string[];
            /**
             * @example [
             *       "Балкон",
             *       "Лоджия"
             *     ]
             */
            features?: string[];
            /** @enum {string} */
            status?: "ACTIVE" | "PENDING" | "SOLD" | "ARCHIVED";
            /**
             * @description Широта
             * @example 43.3156
             */
            latitude?: number;
            /**
             * @description Долгота
             * @example 45.6949
             */
            longitude?: number;
        };
        FavoriteResponseDto: {
            id: string;
            userId: string;
            propertyId: string;
            /** Format: date-time */
            createdAt: string;
            property: components["schemas"]["PropertyResponseDto"];
        };
        UpdateUserRoleDto: {
            /** @enum {string} */
            role: "USER" | "PREMIUM" | "ADMIN" | "SUPPORT";
        };
        UpdatePropertyStatusDto: {
            /** @enum {string} */
            status: "ACTIVE" | "PENDING" | "SOLD" | "ARCHIVED";
        };
        CreatePropertyChatDto: {
            /**
             * @description ID объявления недвижимости
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            propertyId: string;
        };
        ChatParticipantResponseDto: {
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id: string;
            /** @example 550e8400-e29b-41d4-a716-446655440001 */
            userId: string;
            /**
             * @example BUYER
             * @enum {string}
             */
            role: "BUYER" | "SELLER" | "SUPPORT";
        };
        ChatResponseDto: {
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id: string;
            /**
             * @example PROPERTY
             * @enum {string}
             */
            type: "PROPERTY" | "SUPPORT";
            /** @example 550e8400-e29b-41d4-a716-446655440001 */
            propertyId: string | null;
            /** @example false */
            isArchived: boolean;
            /**
             * Format: date-time
             * @example 2024-01-20T10:30:00Z
             */
            lastMessageAt: string | null;
            /** @example Здравствуйте, интересует ваше объявление */
            lastMessageText: string | null;
            /**
             * Format: date-time
             * @example 2024-01-20T10:00:00Z
             */
            createdAt: string;
            participants: components["schemas"]["ChatParticipantResponseDto"][];
            /**
             * @description Количество непрочитанных сообщений
             * @example 0
             */
            unreadCount: number;
            /** @description Информация об объявлении (если тип PROPERTY) */
            property?: Record<string, never>;
        };
        MessageResponseDto: {
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id: string;
            /** @example 550e8400-e29b-41d4-a716-446655440001 */
            chatId: string;
            /** @example 550e8400-e29b-41d4-a716-446655440002 */
            senderId: string;
            /** @example Здравствуйте, интересует ваше объявление */
            text: string;
            /** @example false */
            isRead: boolean;
            /**
             * Format: date-time
             * @example null
             */
            readAt: string | null;
            /**
             * Format: date-time
             * @example 2024-01-20T10:30:00Z
             */
            createdAt: string;
        };
        MessagesResponseDto: {
            messages: components["schemas"]["MessageResponseDto"][];
            /**
             * @description ID следующего сообщения для cursor pagination (null если это последняя страница)
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            nextCursor: string | null;
            /**
             * @description Есть ли еще сообщения для загрузки
             * @example true
             */
            hasMore: boolean;
        };
        SendMessageDto: {
            /**
             * @description Текст сообщения
             * @example Здравствуйте, интересует ваше объявление
             */
            text: string;
        };
        AssignSupportDto: {
            /**
             * @description ID сотрудника поддержки для назначения
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            supportUserId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_sendPhoneCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendPhoneCodeDto"];
            };
        };
        responses: {
            /** @description Код отправлен */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Невалидный номер телефона */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Слишком много попыток */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_verifyPhoneCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyPhoneCodeDto"];
            };
        };
        responses: {
            /** @description Успешная аутентификация */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Неверный или истёкший код */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_registerWithPhoneAndPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPhonePasswordDto"];
            };
        };
        responses: {
            /** @description Пользователь зарегистрирован */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_loginWithPhoneAndPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешная аутентификация */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_yandexAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_yandexCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            /** @description Токен обновлен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refresh token недействителен */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Выход выполнен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Информация о пользователе */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Профиль пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            /** @description Профиль обновлен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Информация о пользователе */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Пользователь не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PropertiesController_findAll: {
        parameters: {
            query?: {
                query?: string;
                type?: "APARTMENT" | "HOUSE" | "LAND" | "COMMERCIAL";
                priceMin?: number;
                priceMax?: number;
                rooms?: number;
                areaMin?: number;
                regionId?: string;
                /** @description Фильтр по городу */
                cityId?: string;
                sortBy?: "price-asc" | "price-desc" | "date-desc" | "relevance";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список объявлений */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PropertiesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePropertyDto"];
            };
        };
        responses: {
            /** @description Объявление создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyResponseDto"];
                };
            };
        };
    };
    PropertiesController_search: {
        parameters: {
            query: {
                /** @description Поисковый запрос */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Результаты поиска */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyResponseDto"][];
                };
            };
        };
    };
    PropertiesController_getCategoryStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Статистика по категориям */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PropertiesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Информация об объявлении */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyResponseDto"];
                };
            };
            /** @description Объявление не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PropertiesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Объявление удалено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет доступа */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Объявление не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PropertiesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePropertyDto"];
            };
        };
        responses: {
            /** @description Объявление обновлено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyResponseDto"];
                };
            };
            /** @description Нет доступа */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Объявление не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavoritesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список избранного */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteResponseDto"][];
                };
            };
        };
    };
    FavoritesController_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Объявление добавлено в избранное */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteResponseDto"];
                };
            };
            /** @description Объявление не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Объявление уже в избранном */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavoritesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Объявление удалено из избранного */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Объявление не найдено в избранном */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_getStatistics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Статистика получена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_getUsers: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список пользователей */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_getProperties: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
                status?: "ACTIVE" | "PENDING" | "SOLD" | "ARCHIVED";
                type?: "APARTMENT" | "HOUSE" | "LAND" | "COMMERCIAL";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список объявлений */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_updateUserRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRoleDto"];
            };
        };
        responses: {
            /** @description Роль изменена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_updatePropertyStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePropertyStatusDto"];
            };
        };
        responses: {
            /** @description Статус изменен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пользователь удален */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_deleteProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Объявление удалено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UploadController_uploadAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Изображение (jpg, png, webp), max 5MB
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Аватар успешно загружен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example https://res.cloudinary.com/... */
                        avatar?: string;
                    };
                };
            };
            /** @description Некорректный запрос */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Файл слишком большой */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Неподдерживаемый формат */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UploadController_uploadImages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description Изображения (jpg, png, webp), max 10 файлов, каждый max 5MB */
                    files: string[];
                };
            };
        };
        responses: {
            /** @description Изображения успешно загружены */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        images?: {
                            /** @example https://res.cloudinary.com/... */
                            url?: string;
                            /** @example dohkar/properties/abc123 */
                            publicId?: string;
                        }[];
                    };
                };
            };
            /** @description Некорректный запрос */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Файл слишком большой */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Неподдерживаемый формат */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatsController_createPropertyChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePropertyChatDto"];
            };
        };
        responses: {
            /** @description Чат создан или получен */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponseDto"];
                };
            };
            /** @description Нельзя создать чат со своим объявлением */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Объявление не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatsController_createSupportChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Чат поддержки создан или получен */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponseDto"];
                };
            };
        };
    };
    ChatsController_getUserChats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список чатов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponseDto"][];
                };
            };
        };
    };
    ChatsController_getChatMessages: {
        parameters: {
            query?: {
                /** @description Cursor для пагинации (ID последнего загруженного сообщения) */
                cursor?: string;
                /** @description Количество сообщений для загрузки */
                limit?: number;
            };
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список сообщений */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagesResponseDto"];
                };
            };
            /** @description Нет доступа к чату */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Чат не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatsController_sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageDto"];
            };
        };
        responses: {
            /** @description Сообщение отправлено */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
            /** @description Запрещенный контент в первых двух сообщениях */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет доступа к чату */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Чат не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Превышен лимит запросов */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatsController_markMessagesAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сообщения помечены как прочитанные */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет доступа к чату */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Чат не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatsController_getSupportChats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список всех чатов поддержки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponseDto"][];
                };
            };
            /** @description Нет прав доступа */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatsController_assignSupportAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignSupportDto"];
            };
        };
        responses: {
            /** @description Сотрудник поддержки назначен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Некорректные данные */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет прав доступа */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Чат не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RegionsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список регионов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RegionsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Регион с городами */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Регион не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CitiesController_findCities: {
        parameters: {
            query?: {
                /** @description Фильтр по региону (UUID) */
                regionId?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список городов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
